name: basicshare
description: "A simple app around Basic-Fit"
publish_to: 'none'
version: 1.0.1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: any
  shared_preferences: ^2.0.8
  flutter_spinkit: ^5.2.1
  cupertino_icons: ^1.0.6
  sizer: ^3.0.3
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_inappwebview: ^6.1.5
  crypto: ^3.0.6
  qr_flutter:
    git:
      url: https://github.com/szerookii/qr.flutter.git
      ref: 63ce311d8ce2e0d46a7e8a00f56e164fbeaf4332
  screen_brightness: ^2.0.1
  intl: ^0.20.1
  fl_chart: ^0.70.1
  quick_settings: ^1.0.1

dev_dependencies:
  build_runner:
  custom_lint:
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.3"

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21